language: java

sudo: false

jdk:
  - openjdk11

cache:
  directories:
    - $HOME/.m2

script: ./mvnw clean verify --no-transfer-progress

after_success:
  - ./mvnw coveralls:report --no-transfer-progress

notifications:
  email:
    on_failure: change
