language: java

sudo: false

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

script: ./mvnw clean verify

after_success:
  - ./mvnw coveralls:report

notifications:
  email:
    on_failure: change
