language: java

sudo: false

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

script: mvn clean verify

after_success:
  - mvn coveralls:report

notifications:
  email:
    on_failure: change
