name: build

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
  schedule:
  - cron: "0 6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Cache
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: m2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Compile
      run: ./mvnw clean test-compile -B
    - name: Test
      run: ./mvnw verify -B
